### ISSUE TITLE
cell错位

### ISSUE THREAD

**Issue by kallyWang** [MonkeyS914/SCSwipeTableViewCell#1]
如果我的tableView中有其它类型的cell，你封装的这种cell就错位了

**Comment by MonkeyS914** [comment]
请问下具体是什么情况错位吗？是cell的整体位置不对，还是滑动时露出的btn错位了，谢谢

**Comment by kallyWang** [comment]
额，我是tableView的section1中是其它类型的；section2中的cell需要有删除编辑功能，有多行，使用时，section2中只显示了第一行。然后左滑section2中的第一行，应该出现在第一行的编辑删除框出现在了section2的第二行

补充一下，是当cell的高度不一致时，就会出现这种bug

**Comment by MonkeyS914** [comment]
我刚刚建了一个demo，两个section，section1三个默认的cell，section2三个SCSwipeTableViewCell，然后滑动，没有出现错位显示的问题，可不可以把你出问题的那部分代码发给我看看。4919668@qq.com，谢谢

**Comment by kallyWang** [comment]
- (void)processBtns{
  CGFloat lastWidth = 0;
  int i = 0;
  NSIndexPath *indexPath = [_superTableView indexPathForCell:self];
  if (indexPath) {
      self.cellHeight = [_superTableView rectForRowAtIndexPath:indexPath].size.height;
  }else {
      self.cellHeight = [self myCellHeight];
  }

问题在于：不同cell的高度不一样， self.cellHeight =。。。这句改一下就好了。self.cellHeigh的高度可以由外部传入

**Comment by MonkeyS914** [comment]
bug已经fixed，见new version1.0.4
